ame: Convert Jupyter Notebook to HTML
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:  # Разрешает ручной запуск

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install jupyter nbconvert

      - name: Convert notebook to HTML
        run: |
          jupyter nbconvert --to html master/ML_supervised_learning_project.ipynb # Замените на ваш файл .ipynb

      - name: Upload HTML as artifact
        uses: actions/upload-artifact@v3
        with:
          name: notebook-report
          path: master/notebook.html  # Путь к сгенерированному HTML
